Dev simone
BeatingCodingame/python3-code-vs-zombie pull request #18
Opened 2020-11-16 10:02 UTC by Symone95

Hi @GiovanniCardamone,
In 6c6201a027858e15df0cfa423b19d958dd7f4508 commit I've Implemented Behaviour class with inheritance to handle Ash's behaviours in various situations

Simone

2020-11-16 15:56 UTC, GiovanniCardamone commented
Send me a PM when this is ready

2020-11-19 09:28 UTC, Symone95 commented
Hi @GiovanniCardamone,
I've implemented poetry to run testcases in this commit: 2af2cdf6b1e199843ec3a3749d7e3a07a73c3388

Simone

2020-11-19 10:03 UTC, GiovanniCardamone commented
the test fails https://github.com/BeatingCodingame/python3-code-vs-zombie/pull/18/checks

2020-11-19 10:03 UTC, GiovanniCardamone commented
i will do a review of this PR, please fix it so i can merge

2020-11-19 10:06 UTC, GiovanniCardamone requested changes
The actions should only use poetry as dependencies manager

2020-11-19 10:06 UTC, GiovanniCardamone commented on .github/workflow/python-package.yml
> +        python -m pip install --upgrade pip
you should use only poetry to install the dependencies

2020-11-19 10:06 UTC, GiovanniCardamone commented on .github/workflow/python-package.yml
> +    - run: poetry run pytest
missing dependencies install using poetry

2020-11-19 11:31 UTC, GiovanniCardamone commented
rejected

2020-11-19 11:31 UTC, closed without merging